### ISSUE TITLE
get_stocks_data loop endless if token is empty

### ISSUE THREAD

**Issue by OpenDGPS** [dm13450/AlpacaMarkets.jl#5]
The `while !isnothing(token)` will give 'true' if the 'token::String' is empty. 

With `while (!(token == "") && !isnothing(token))` it works.

While the last token for the pagination is set to nothing, a call for a time period with initial zero records comes with an empty token. 

Add: maybe a parameter or ENV for `sleep(0.301)`would be nice.

[Edit: difference between the two cases.]

**Comment by dm13450** [comment]
Just pushed a change that should fix the endless loop. 
Plus, `get(ENV, "ALPACA_SLEEP", "0.301")` in you ENV will allow you to change the sleep time.

**Comment by dm13450** [comment]
Fixed in 0.1.1
